services:
  listinator:
    image: ghcr.io/hacky-day/listinator:latest
    ports:
      - 8080:8080
    environment:
      LISTINATOR_DATABASE_DIR: /var/lib/listinator
      LISTINATOR_SESSION_SECRET: changeme
      LISTIANTOR_ADMIN_PASSWORD: changeme
    volumes:
      - ./data:/var/lib/listinator

