services:
  listinator:
    image: ghcr.io/shaardie/listinator:latest
    ports:
      - 8080:8080
    environment:
      LISTINATOR_DATABASE_DIR: /var/lib/listinator
    volumes:
      - ./data:/var/lib/listinator

