services:
  core:
    # image: ghcr.io/hacky-day/listinator-core:latest
    build:
      context: ../core
    ports:
      - 8080:8080
    environment:
      LISTINATOR_DATABASE_DIR: /var/lib/listinator
      LISTINATOR_SESSION_SECRET: changeme
      LISTINATOR_ADMIN_PASSWORD: changeme
      LISTINATOR_TYPIFIER_URL: http://typifier:8000
    volumes:
      - ./data:/var/lib/listinator
  typifier:
    # image: ghcr.io/hacky-day/listinator-typifier:latest
    build:
      context: ../typifier
    environment:
      UVICORN_HOST: "0.0.0.0"
    ports:
      - 8000:8000
