services:
  caddy:
    image: caddy  # use tag in production
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
        LISTINATOR_ADDRESS: "*"
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./conf:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - external
      - internal
  listinator:
    # image: ghcr.io/hacky-day/listinator:latest
    build:
      context: ../
    restart: unless-stopped
    environment:
      LISTINATOR_DATABASE_DIR: /var/lib/listinator
      LISTINATOR_SESSION_SECRET: changeme
      LISTINATOR_ADMIN_PASSWORD: changeme
    volumes:
      - listinator_data:/var/lib/listinator
    networks:
      - internal

volumes:
  caddy_data:
  caddy_config:

  listinator_data:

networks:
  internal:
    internal: true
  external:
